abw/Template2

- lib/Template/Stash.pm
> POD fix (link syntax)

- lib/Template/VMethods.pm
When sorting a list by multiple numeric keys, many warnings are produced:
```
[% SET things = [
{
'foo' => 1,
'bar' => 1,
},
{
'foo' => 1,
'bar' => 2,
},
{
'foo' => 2,
'bar' => 1,
},
] %]
[% FOREACH thing IN things.nsort("foo", "bar") %]
[% thing.foo %] [% thing.bar %]
[% END %]
```
> Argument "1/*^unlikely^*/2" isn't numeric in numeric comparison (<=>) at > /usr/lib/perl5/site_perl/5.8.8/i386-linux-thread-multi/Template/VMethods.pm line 574.
> Argument "1/*^unlikely^*/1" isn't numeric in numeric comparison (<=>) at /usr/lib/perl5/site_perl/5.8.8/i386-linux-thread-multi/Template/VMethods.pm line 574.
> Argument "2/*^unlikely^*/1" isn't numeric in numeric comparison (<=>) at /usr/lib/perl5/site_perl/5.8.8/i386-linux-thread-multi/Template/VMethods.pm line 574.
> Fixing warnings in list_nsort when sorting by multiple fields.

- testrules.yml
Since t/compile1.t creates the cache for the other compile*.t tests, it cannot be run parallel and must be explicitly set to run sequentially.
Fixes RT 99576 and should fix a couple CPAN Tester Reports ([example](http://www.cpantesters.org/cpan/report/3e55a648-91c9-11e4-8169-9f55a5948d86))
> Added testrules.yml to always run compile*.t sequentially

- lib/Template/Manual/VMethods.pod
- lib/Template/VMethods.pm
- t/vmethods/hash.t
- t/vmethods/list.t
- t/vmethods/text.t
I often find myself doing things like this:
[% IF 0 == details.size %]                                                      
No details specified                                                     
[% END %] 
For convenience and brevity, it would be nice to have a `scalar` vmethod so that one could instead write
[% IF details.empty %]                                                      
No details specified                                                     
[% END %]
> Add 'empty' vmethods for scalar, list and hash

- MANIFEST
- lib/Template/Toolkit.pm
(this branch ties in with #32)
It happens fairly often that someone does
$ cpanm Template::Toolkit
and wonder why CPAN doesn't find the distribution.
Moving the main pod to a `.pm` would index it, and
take care of that.
> Make Template::Toolkit a module

- lib/Template/Parser.pm
- t/block_duplicate.t
Before, Template would silently ignore all previous definitions of the
block.
See also https://github.com/ingydotnet/jemplate/issues/8 .
> Warn on duplicate block name.

- lib/Template/Plugin/Dumper.pm
This change allows sorting the keys in the output of dumper (convenient when reproducing the same output over and over again during debugging).
> Add Sortkeys to DUMPER_ARGS

- .travis.yml
- Makefile.PL
- lib/Template/Config.pm
Only non-.travis.yml change was that perl Makefile.pl failed for 5.26 because '.' is pulled from @INC, so I changed '.defaults.cfg' to './.defaults.cfg'
> Added Travis-CI Testing

- t/process_dir.t
Template failed test process_dir.t because external "rm -rf" call is
made in that file. That command doesn't exist on Win32 system. It is
possible to use remove_tree from File::Path. There is also a condition
with expected2 that need some adjustment.
Below error message from test:
'rm' is not recognized as an internal or external command,
operable program or batch file.
'rm' is not recognized as an internal or external command,
operable program or batch file.
t/process_dir.t .......
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/5 subtests
I hope you will agree my pull request. Thanks for that great module.
> remove rm external system command call

- t/cgi.t
GH #96 
This is forcing the scalar context when calling CGI::param during unit tests to avoid the warning from CGI.
> Force scalar context for CGI param

- t/filter.t
GH #179
With commit b0620f4 we start using RFC3986 as default
for URI but the test was not adjusted according to this
new setting.
> Adjust t/filter.t after using RFC3986 as default for URI

- lib/Template/Stash.pm
- xs/Stash.xs
Discovered this issue while running the test suite
with travis and realized that t/cgi.t which is now
using Template::Plugin::Scalar was not working as
expected for Perl 5.18 and earlier...
The regexp on $@ is kind of very fragile.
Extend the existing regexp as part of the first commit, then convert it to a 'can' usage
> Template stash  dotop

- Makefile.PL
set bug tracker as https://github.com/abw/Template2/issues
and the homepage website to be http://www.template-toolkit.org
> Use GitHub as official bug tracker

- lib/Template/Directive.pm
This is a micro optimization to speedup the
quotes stripping.
From a simple Benchmark::Dumb test it appears to be 25 to 35 %
faster. View GitHub case for benchmark script.
Here is a naive benchmark test proving the speedup advantage of the index usage vs the substr one liner.
```perl
#!perl
use strict;
use warnings;
use Benchmark::Dumb qw(:all);
my @noquotes = qw{some values without quotes};
my @quotes   = qw{'with' 'a' 'quote' 'longworwithaquote'};
for ( 1..10 ) {
push @noquotes, @noquotes;
push @quotes, @quotes;	
}
my @mix = @quotes, @noquotes;
print "# Strings with quotes\n";
compare( \@quotes );
print "# Strings without quotes\n";
compare( \@noquotes );
print "# A mixed of both: 50/50\n";
compare( \@mix );
sub compare {
my ( $input ) = @_;
cmpthese(
0.01,    # 1% precision
{ …
```
> Check string with index before substitute

- lib/Template/Parser.pm
This is an optimization which avoids creating
an anonymous sub then call it inside an eval
block.
> Avoid a dummy sub in Template::Parser

- xs/Stash.xs
convert_dotted_string can benefit from
a pre allocated buffer, avoiding the malloc + free.
> use pre allocated buffer in Stash.xs

- MANIFEST
- lib/Template/Plugin/Math.pm
- t/math_rand.t
Resolves GH #155: Calling this without an arg caused the following error:
Use of uninitialized value $_[0] in rand at
/usr/lib/perl5/Template/Plugin/Math.pm line 55.
The issue is fixed and tests are added to confirm this works correctly in
the future.
> Fix for rand call with no args in Math plugin.

- lib/Template/Plugin/Filter.pm
- t/zz-plugin-cycle.t
GH #152
This is an issue reported by hiratara who detected
a memory leak in Template::Plugin::Filter.
This commit adds one extra dev test to check for memory
leak and report circular reference found, in order
to detect similar issues in the future.
The leak is fixed by using weaken on the context object
stored in Plugin::Filter.
References: RT 62045
> Fix a circular reference in Template::Plugin::Filter

- MANIFEST
- t/process-relative.t
GH #122:
This is providing some tests to cover the case
described by RT 91172 where './file' cannot be
processed without having RELATIVE set
even if '.' is in INCLUDE_PATH.
We do not want to handle the special case where:
INCLUDE_PATH => '.'
file         => './file'
as the file could be anything like './../../../file'
When using './file' you need to set RELATIVE to true.
> Add unit tests for processing file or ./file

- MANIFEST
- lib/Template/Plugin/Filter.pm
- t/zz-plugin-leak-rt-46691.t
Fixup on GH #152
This is adding a test from GH #144 showing how
an incorrect weaken can break plugins.
Then it's patching correctly the circular reference when
building the filter using the factory.
> Improve the weaken patch in Plugin::Filter

- lib/Template/Provider.pm
Resolves #204
Avoid release permissions issues by removing
the 'package bytes'. We just try to avoid to load it.
Note: newline can also hide it from PAUSE but this is not
necessary in this case.
> No need to declare package bytes

- lib/Template/Plugin/Filter.pm
Fixes #206.
The following minimal example reproduces the error:
```perl
package Template::Plugin::Echo;
use base qw(Template::Plugin::Filter);
sub filter {
my ($self, $text) = @_;
return $text . $text;
}
package main;
use Template;
$INC{'Template/Plugin/Echo.pm'} = 'whatever';
my $template = <<'EOF';
[%- USE Echo -%]
[% FILTER $Echo %]foo[% END %]
[% FILTER $Echo %]bar[% END %]
EOF
Template->new->process(\$template, {}) or die $Template::Error;
```
The warning "reference is already weak at ..." only appears if you use the `FILTER` more than once. The warning disappears if you remove the last line from `$template`.
The issue may look like a minor, cosmetic problem but in larger projects it is a major nuisance because you are getting flooded with warnings.
> do not weaken cyclic reference twice

- lib/Template/Base.pm
Compiled code using Template::Toolkit object
segfault during fast_destroy.
The stash cache is corrupted, for one unknown
reason. Provide an empty DESTROY sub to Template::Base
> Avoid destruction segfault on Template objects

- lib/Template/Directive.pm
- t/constants.t
- t/fileline.t
Because Perl has to do less work to parse a '' string than a "" string, we
can detect this and generate '' when rendering the template.
This change may require more tests.
> Speed up Template Toolkit template by about 10% with single quotes

- lib/Template/Context.pm
Template::Toolkit lacked the logic to determine if a plugin is
already loaded into a context and will reload the plugin every
time it sees a USE statement.
> Ensure we only load plugins once per context

- lib/Template/Iterator.pm
Autoload is somewhat expenseive and index, count, first, last, size are
trivial subroutines. Let's just declare them.
> Optimize get_next overhead for frequent calls by avoiding AUTOLOAD.

- lib/Template/Iterator.pm
Templates which make heavy use of loops to render UIs will notice better
performance with this change.
Avoid AUTOLOAD for frequent method calls such as index, count,
size, etc as its quite expensive
> Reduce Template Toolkit get_next overhead

- lib/Template/Plugin/Date.pm
Resolves GH #116
date.format(0) returns todays date not 01/01/1970
i.e. there needs to be a difference between
date.format(0)
and
date.format()
> Set date to epoch when doing date.format(0)

- Changes
- Makefile.PL
- lib/Template/Config.pm
- lib/Template/Constants.pm
- lib/Template/Plugin/Date.pm
- lib/Template/Tutorial/Web.pod
- t/base.t
- t/config.t
- t/dumper.t
- t/leak.t
- t/object.t
- t/output.t
- t/stop.t
- todo_misc/cache_plugin
We are already using some features which are
failing with 5.6.
> Remove 'use vars' and drop officialy 5.6 support.

- .github/workflows/linux.yml
- cpanfile
- lib/Template/Context.pm
References #241
We cannot cache Autoformat plugin as
it contains some filters which would
not be reset on the second load.
This is a follow up to commit
282109bf1a49ef8c0848a31d960260a116d91a4f
> Do not cache plugin with filters

- .github/workflows/linux.yml
- .github/workflows/plugins.yml
- Changes
- cpanfile.plugins
- lib/Template/Context.pm
- lib/Template/Provider.pm
This reverts "Ensure we only load plugins once per context" from commit 282109bf1a49ef8c0848a31d960260a116d91a4f and fixes GH #241
This is also providing an additional workflow dedicated to plugins to avoid such regression in the future.
> Fix and smoke Template plugins

- lib/Template/Manual/Variables.pod
I had noticed that one of the comments didn't match the content that it was referring to.
P.S. Happy New Year
> Typo fix in Variables.pod

- lib/Template/Plugin/Datafile.pm
This PR add ability to specify 'encoding' option when opening file in the 'Datafile' plugin.
E.g. opening file in UTF-8 encoding:
[% USE file = datafile('foo.csv', encoding = 'UTF-8') %]
> Add encoding option to Datafile plugin

- lib/Template/Directive.pm
- t/while.t
This fix was done as part of the CV-Library pull request.
The fix was a change to the logic for WHILE_MAX to ensure it does not double count and fail before the limit is reached.
> Fix Issue 149 - WHILE_MAX setting does not seem to work

- lib/Template/Plugin/Date.pm
- t/date.t
This is an attempt at solving #132 in a way that maintains backwards compatibility (and avoid the issues that blocked #192).
This is implemented not in a separate function, but with a separate `use_offset` parameter that can be set globally for those who like to live on the edge. The parameter can be set by name or as the fifth (!) parameter to `format`.
I am not entirely convinced on the name of the parameter, so I am open to suggestions for a better name. 
This contribution brought to you courtesy of the Pull Request Challenge. :)
> Add support for %z. Fix #132

- bin/ttree
This PR implements assets directories in ttree.
Assets directories are directories that contain assets, fixed (static) materials that are not to be processed by Template, but always copied 'as is'. Common use is for static images, icons, documentation files, videos and so on.
The PR adds the keyword `assets` and corresponding command line option `--assets` that can be used to name a directory that contains assets. This directory must reside directly under the top of the source tree. Multiple directories can be specified by repeating the keyword or command line option.
When asset directories are specified, all files in these directories are copied with two exceptions:
* filenames that match any of the ignore patterns are ignored
* filenames that match any of the link patterns are linked …
> ttree: Implement assets directories.

- bin/ttree
Giving everything a second thought, I think that your idea to name it `copy_dir` is actually better. As it is implemented this is exactly what it is: it copies the dir like it would have copied the individual files based on `copy` patterns.
That this can be used for things like assets is a different matter.
> ttree: Rename --assets to --copy_dir.

- lib/Template/Document.pm
- lib/Template/Provider.pm
This silences these warnings:
t/compile1.t ................. each on anonymous hash will always start from the beginning at lib/Template/Document.pm line 75.
each on anonymous hash will always start from the beginning at lib/Template/Provider.pm line 373.
each on anonymous hash will always start from the beginning at lib/Template/Provider.pm line 872.
each on anonymous hash will always start from the beginning at lib/Template/Provider.pm line 891.
when compiling Template.  These warnings are still generated as of 5.35.4
@trwyant had alternate suggestions in #287 which also may be fine, but I needed to make these changes in my environment now and figured I may as well make it a PR while I was at it.  If you want a different implementation no harm in closing this.
> Avoid anonymous hash warnings starting with Perl 5.35.2

- lib/Template/Test.pm
- lib/Template/Tutorial/Web.pod
Template has never had an import method, so passing arguments to it is pointless. The import call has always just been ignored by perl, but in the future it will trigger an error if given unhandled arguments.
> remove extraneous arguments when loading Template

- lib/Template/Manual/Variables.pod
I found out that Variables manual, do not have info how to address hash element with complex key , like `example.txt` for example 
This might cause real problem for Template Toolkit newbie. So I'd suggest a fix that adds another method of accessing hash value from hash to the Variables pod.
PS. Please refer me as Nikolay Shaplov (NATARAJ) in changelog, if you ever will refer me...
> Fix manual. Added info about accessing values with comples keys from hash

- lib/Template/Provider.pm
This is a fix for #158 as the regex that was used on Windows was not correct (it was missing an alternation between the slash and backslash).
> Correct the path splitting on Win32

- lib/Template/App/ttree.pm
This fixes issue #325 by ensuring that the totals (all the n_* variables) are set as references in the `$running_conf` hashref so that the changed values are reflected in the calling routines.
> Make ttree totals references (issue #325)

- bin/ttree
- lib/Template/App/ttree.pm
- lib/Template/Filters.pm
- lib/Template/Manual/Config.pod
relvant => relevant
dyanamic => dynamic
> Fix 2 typos in comments
